### ISSUE TITLE
ViewData and Node.Fuzzy

### ISSUE THREAD

**Issue by steffendsommer** [nodes-vapor/admin-panel-provider#17]
Figure out how to handle/avoid the `ViewData` type being added to `Node.fuzzy`. @BrettRToomey knows the details.

**Comment by BrettRToomey** [comment]
I don't think there's a whole lot we can do other than document and support alternate versions as fallbacks (like we currently do).

**Comment by siemensikkema** [comment]
@BrettRToomey Speaking of alternate version, check out: https://github.com/nodes-projects/urbanest-vapor/blob/a6aec7a3f2db3e27d1dc334bbee17a31e89a8c4c/Sources/App/Support/ViewDataKey.swift

It allows you to do stuff like:

```swift
ViewData([.request: request, .fieldset: fieldset, "custom key": someNodeRepresentable])
```

**Comment by steffendsommer** [comment]
@BrettRToomey Ye I agree - let's at least mention it in readme then before closing this issue.

**Comment by steffendsommer** [comment]
Already in there I see. Fixed by https://github.com/nodes-vapor/admin-panel-provider/pull/29
