### ISSUE TITLE
Why is mysql-provider a dependency?

### ISSUE THREAD

**Issue by MrMage** [nodes-vapor/admin-panel-provider#35]
The package manifest (https://github.com/nodes-vapor/admin-panel-provider/blob/master/Package.swift) contains this line:

            .Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 2),

yet the code doesn't reference MySQL explicitly anywhere. So why is this a dependency? Could this package be used with a PostgreSQL database (and the corresponding Fluent provider) as well?

**Comment by martinlasek** [comment]
I will look into it if it's possible

**Comment by steffendsommer** [comment]
@MartinLasek consider looking into this one at the same time: https://github.com/nodes-vapor/audit-provider/issues/11

**Comment by MrMage** [comment]
Indeed. Thanks @steffendsommer for making the cross-reference!

**Comment by MrMage** [comment]
Looks like this got fixed a while ago with ba3d6d82bfffa40b8aadbb3d18e41be81f61f162. Thanks @MartinLasek!
